index:
    path: /
    controller: App\Controller\TestController::index

test:
    path: /test
    controller: App\Controller\TestController::test

insertPatient:
    path: /insertPatient
    controller: App\Controller\TestController::insertPatient

getPatient:
    path: /getPatient
    controller: App\Controller\TestController::getPatient

insertDoctor:
    path: /insertDoctor
    controller: App\Controller\TestController::insertDoctor

getDoctor:
    path: /getDoctor
    controller: App\Controller\TestController::getDoctor
