index:
    path: /
    controller: App\Controller\TestController::index

test:
    path: /test
    controller: App\Controller\TestController::test

insertPatient:
    path: /insertPatient
    controller: App\Controller\TestController::insertPatient

getPatient:
    path: /getPatient
    controller: App\Controller\TestController::getPatient

insertProfessional:
    path: /insertProfessional
    controller: App\Controller\TestController::insertProfessional

getProfessional:
    path: /getProfessional
    controller: App\Controller\TestController::getProfessional

# Patient routes

registerPatient:
    path: /patient/register
    controller: App\Controller\PatientAuthentification\Register::register
    methods: [POST]

loginPatient:
    path: /patient/login
    controller: App\Controller\PatientAuthentification\Login::login
    methods: [POST]

linkPatient:
    path: /patient/link
    controller: App\Controller\link\LinkUser::link
    methods: [POST]

getLinkedPatient:
    path: /patient/getLinked
    controller: App\Controller\link\LinkUser::getLinkedPatient
    methods: [GET]

# Professional routes

registerProfessional:
    path: /professional/register
    controller: App\Controller\ProfessionalAuthentification\Register::register
    methods: [POST]

loginProfessional:
    path: /professional/login
    controller: App\Controller\ProfessionalAuthentification\Login::login
    methods: [POST]

linkProfessional:
    path: /professional/link
    controller: App\Controller\link\LinkUser::generateCode
    methods: [GET]

getLinkedProfessional:
    path: /professional/getLinked
    controller: App\Controller\link\LinkUser::getLinkedDoctor
    methods: [GET]

# Swagger routes

app.swagger.ui:
    path: /api/doc
    methods: [GET]
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: [GET]
    defaults: { _controller: nelmio_api_doc.controller.swagger }
