index:
    path: /
    controller: App\Controller\TestController::index

test:
    path: /test
    controller: App\Controller\TestController::test

insertPatient:
    path: /insertPatient
    controller: App\Controller\TestController::insertPatient

getPatient:
    path: /getPatient
    controller: App\Controller\TestController::getPatient

insertDoctor:
    path: /insertDoctor
    controller: App\Controller\TestController::insertDoctor

getDoctor:
    path: /getDoctor
    controller: App\Controller\TestController::getDoctor

registerPatient:
    path: /patient/register
    controller: App\Controller\PatientAuthentification\Register::register
    methods: [POST]

loginPatient:
    path: /patient/login
    controller: App\Controller\PatientAuthentification\Login::login
    methods: [POST]

app.swagger.ui:
    path: /api/doc
    methods: [GET]
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: [GET]
    defaults: { _controller: nelmio_api_doc.controller.swagger }
