<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRRefQxx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRRefQxx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRRefQxx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRRefQxx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRRefQxx\App_KernelDevDebugContainer([
    'container.build_hash' => 'RRefQxx',
    'container.build_id' => '4e65af83',
    'container.build_time' => 1681565211,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRRefQxx');
