name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.ORG_DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.ORG_DOCKER_PASSWORD }}
        DOCKER_REGISTRY: docker.io
      run: |
        echo $secrets
        docker buildx create --use
        docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker buildx build . --file Dockerfile --tag $DOCKER_REGISTRY/my-image-name:$(date +%s) --push
