name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Run tests
        run: npm run test

      # Étape pour vérifier la couverture des tests Jest
      - name: Check Jest coverage
        run: |
          COVERAGE_THRESHOLD=90  # Couverture minimale souhaitée
          JEST_COVERAGE=$(cat coverage/lcov-report/index.html | grep -oP "data-covered=\"\K[^\"]+")
          if (( $(echo "$JEST_COVERAGE >= $COVERAGE_THRESHOLD" | bc -l) )); then
            echo "La couverture des tests Jest est suffisante ($JEST_COVERAGE%)."
          else
            echo "La couverture des tests Jest ($JEST_COVERAGE%) ne satisfait pas la condition minimale de $COVERAGE_THRESHOLD%."
            exit 1
          fi
        env:
          CI: true
