name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    # Ajoutez cette étape pour calculer la couverture et vérifier si elle est supérieure à 90%
    - name: Calculer la couverture et vérifier
      run: |
        COVERAGE_THRESHOLD=90  # Couverture minimale souhaitée
        lines=$(cat coverage/lcov-report/index.html | grep 'class="pct high"')
        total_coverage=0
        count=0
        while read -r line; do
          coverage=$(echo "$line" | sed -n 's/.*>\(.*\)<\/td>/\1/p')
          total_coverage=$((total_coverage + ${coverage%%%}))
          count=$((count + 1))
        done <<< "$lines"
        average_coverage=$((total_coverage / count))
        echo "Moyenne de couverture : $average_coverage%"
        if [ $average_coverage -gt $COVERAGE_THRESHOLD ]; then
          echo "La moyenne de couverture est supérieure à 90%."
        else
          echo "La moyenne de couverture n'atteint pas 90%."
          exit 1
        fi
